import tkinter as tk
from tkinter import ttk

def setup_game_extract_tab(app, tab):
    frame = tk.Frame(tab, **app.frame_style)
    frame.pack(pady=10)
    ttk.Label(frame, text="Select Scripts Folder:", background="#222222", foreground="#FF8C00").pack(pady=5)
    ttk.Entry(frame, textvariable=app.folder_path, width=50).pack(pady=5)
    app.browse_button = ttk.Button(frame, text="Browse", command=app.select_folder, style="TButton")
    app.browse_button.pack(pady=5)
    app.game_label = ttk.Label(frame, text=f"Game: {app.detected_game}", style="TLabel")
    app.game_label.pack(pady=10)
    app.extract_button = ttk.Button(frame, text="Extract Scripts Data", command=app.extract_words_wrapper, style="TButton")
    app.extract_button.pack(pady=5)
    app.progress_bar = ttk.Progressbar(frame, variable=app.progress, maximum=100)
    app.progress_bar.pack(fill="x", pady=5)
    app.result_label = ttk.Label(frame, text="", style="TLabel", foreground="#FFFFFF")
    app.result_label.pack(pady=10)
    app.status_label = ttk.Label(frame, text="", background="#222222", foreground="#00FF00")
    app.status_label.pack(pady=5)

def setup_hash_tab(app, tab):
    frame = tk.Frame(tab, **app.frame_style)
    frame.pack(pady=10)
    ttk.Label(frame, text="Enter String to Hash:", background="#222222", foreground="#FF8C00").pack(pady=5)
    app.hash_input = ttk.Entry(frame, width=30)
    app.hash_input.pack(pady=5)
    app.hash_input.bind("<KeyRelease>", app.update_hash_results)
    app.hash_tree = ttk.Treeview(frame, columns=("Type", "Hash", "String"), show="headings", height=10)
    app.hash_tree.heading("Type", text="Hash Type")
    app.hash_tree.heading("Hash", text="Hash Value")
    app.hash_tree.heading("String", text="Unhashed String")
    app.hash_tree.column("Type", width=120, stretch=tk.NO)
    app.hash_tree.column("Hash", width=200)
    app.hash_tree.column("String", width=200)
    app.hash_tree.pack(fill="both", expand=True, pady=5)
    app.update_hash_results()